name: "pyspark_local"

services:

  spark-master:
    container_name: spark-master
    build: .
    ports:
      - "8080:8080" # Spark master web UI
      - "4040:4040" # Spark UI
      - "7077:7077" # Spark master port
      - "6066:6066" # Spark master cluster port
    volumes:
      - spark-events:/tmp/spark-events
      - ./apps:/opt/spark/apps
      - ./data:/opt/spark/data
    command: spark-class org.apache.spark.deploy.master.Master
    #healthcheck:
    #  test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
    #  interval: 5s
    #  timeout: 3s
    #  retries: 3

  spark-history-server:
    build: .
    ports:
      - "18080:18080" # Spark History server Ui
    depends_on:
      - spark-master
    command: spark-class org.apache.spark.deploy.history.HistoryServer
    volumes:
      - spark-events:/tmp/spark-events

  spark-worker:
    build: .
    deploy:
      mode: replicated
      replicas: 2
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=3G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
    volumes:
      - spark-events:/tmp/spark-events
    depends_on:
      - spark-master
    command: spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    #command: spark-class org.apache.spark.deploy.worker.Worker --properties-file /opt/spark/conf/spark-defaults.conf

volumes:
  spark-events:
